from __future__ import annotations

from pathlib import Path

from sgsl.colors import color_to_rgb
from sgsl.primitives import iter_render_objects


def _load_builder_source() -> str:
    builder_path = Path(__file__).resolve().parents[2] / "roblox" / "Builder.lua"
    source = builder_path.read_text(encoding="utf-8")
    source = source.removesuffix("\n")
    if source.endswith("return Builder"):
        source = source[: -len("return Builder")].rstrip()
    return source


def render(scene: dict, *, mode: str = "standalone", builder_require: str = "game.ReplicatedStorage.SceneLanguagePrimitives") -> str:
    if mode == "standalone":
        return _render_standalone(scene)
    if mode == "module":
        return _render_module(scene, builder_require)
    raise ValueError(f"Unsupported Roblox render mode: {mode}")


def _render_standalone(scene: dict) -> str:
    lines = _header(scene)
    lines.extend(["local Builder = (function()"])
    lines.extend(_indent_lines(_load_builder_source().splitlines()))
    lines.extend(
        [
            "    return Builder",
            "end)()",
            "",
        ]
    )
    lines.extend(_set_transparency_lines())
    lines.extend(
        [
            f"local existing = workspace:FindFirstChild({scene['scene']!r})",
            "if existing then",
            "    existing:Destroy()",
            "end",
            "",
            "local sceneFolder = Instance.new(\"Folder\")",
            f"sceneFolder.Name = {scene['scene']!r}",
            "sceneFolder.Parent = workspace",
            "",
        ]
    )
    lines.extend(_scene_object_lines(scene))
    return "\n".join(lines).rstrip() + "\n"


def _render_module(scene: dict, builder_require: str) -> str:
    lines = _header(scene)
    body = [
        "return function(parent)",
        f"    local Builder = require({builder_require})",
        "",
    ]
    body.extend(_indent_lines(_set_transparency_lines()))
    body.extend(
        [
            "    local sceneParent = parent or workspace",
            f"    local existing = sceneParent:FindFirstChild({scene['scene']!r})",
            "    if existing then",
            "        existing:Destroy()",
            "    end",
            "",
            "    local sceneFolder = Instance.new(\"Folder\")",
            f"    sceneFolder.Name = {scene['scene']!r}",
            "    sceneFolder.Parent = sceneParent",
            "",
        ]
    )
    body.extend(_indent_lines(_scene_object_lines(scene)))
    body.extend(
        [
            "    return sceneFolder",
            "end",
        ]
    )
    lines.extend(body)
    return "\n".join(lines).rstrip() + "\n"


def _header(scene: dict) -> list[str]:
    return [
        "-- Generated by SGSL",
        f"-- Scene: {scene['scene']}",
        "",
    ]


def _set_transparency_lines() -> list[str]:
    return [
        "local function setTransparency(target, transparency)",
        "    if target:IsA(\"BasePart\") then",
        "        target.Transparency = transparency",
        "        return",
        "    end",
        "",
        "    for _, descendant in ipairs(target:GetDescendants()) do",
        "        if descendant:IsA(\"BasePart\") then",
        "            descendant.Transparency = transparency",
        "        end",
        "    end",
        "end",
        "",
    ]


def _scene_object_lines(scene: dict) -> list[str]:
    lines: list[str] = []
    for obj in scene["objects"]:
        red, green, blue = color_to_rgb(obj["color"])
        lines.extend(_render_object(obj, red, green, blue))
    return lines


def _indent_lines(lines: list[str], spaces: int = 4) -> list[str]:
    prefix = " " * spaces
    return [f"{prefix}{line}" if line else "" for line in lines]


def _render_object(obj: dict, red: int, green: int, blue: int) -> list[str]:
    if obj["type"] == "frustum":
        return _render_frustum(obj, red, green, blue)
    if obj["type"] == "ring":
        return _render_ring(obj, red, green, blue)
    return _render_part(obj, red, green, blue)


def _render_part(obj: dict, red: int, green: int, blue: int) -> list[str]:
    x, y, z = obj["position"]
    transparency = obj["transparency"]
    material = "Glass" if transparency > 0 else "SmoothPlastic"
    color_expr = f"Color3.fromRGB({red}, {green}, {blue})"
    material_expr = f"Enum.Material.{material}"

    if obj["type"] == "block":
        sx, sy, sz = obj["size"]
        creator = (
            f"Builder.makeBlock(sceneFolder, {obj['name']!r}, "
            f"Vector3.new({sx}, {sy}, {sz}), Vector3.new({x}, {y}, {z}), {color_expr}, {material_expr})"
        )
    elif obj["type"] == "cylinder":
        creator = (
            f"Builder.makeCylinder(sceneFolder, {obj['name']!r}, "
            f"{obj['radius']}, {obj['height']}, Vector3.new({x}, {y}, {z}), {color_expr}, {material_expr})"
        )
    else:
        raise ValueError(f"Unsupported render object type: {obj['type']}")

    return [
        "do",
        f"    local part = {creator}",
        f"    setTransparency(part, {transparency})",
        "end",
        "",
    ]


def _render_frustum(obj: dict, red: int, green: int, blue: int) -> list[str]:
    x, y, z = obj["position"]
    transparency = obj["transparency"]
    material = "Glass" if transparency > 0 else "SmoothPlastic"
    return [
        "do",
        "    local model = Builder.makeSteppedFrustum(",
        "        sceneFolder,",
        f"        {obj['name']!r},",
        f"        {obj['radius_bottom']},",
        f"        {obj['radius_top']},",
        f"        {obj['height']},",
        f"        Vector3.new({x}, {y}, {z}),",
        f"        Color3.fromRGB({red}, {green}, {blue}),",
        f"        {obj['segments']},",
        f"        Enum.Material.{material}",
        "    )",
        f"    setTransparency(model, {transparency})",
        "end",
        "",
    ]


def _render_ring(obj: dict, red: int, green: int, blue: int) -> list[str]:
    lines: list[str] = []
    for expanded in iter_render_objects({"scene": "", "objects": [obj]}):
        lines.extend(_render_part(expanded, red, green, blue))
    return lines


def write(
    scene: dict,
    output_path: str | Path,
    *,
    mode: str = "standalone",
    builder_require: str = "game.ReplicatedStorage.SceneLanguagePrimitives",
) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(scene, mode=mode, builder_require=builder_require), encoding="utf-8")
    return path
