from __future__ import annotations

import math
from pathlib import Path

from sgsl.colors import color_to_rgb
from sgsl.primitives import (
    _basis_transform,
    _expand_spherical_cap,
    _make_transform,
    _multiply_transforms,
    _transform_position,
    _transform_rotation,
    iter_render_objects,
)


def _load_builder_source() -> str:
    builder_path = Path(__file__).resolve().parents[2] / "roblox" / "Builder.lua"
    source = builder_path.read_text(encoding="utf-8")
    source = source.removesuffix("\n")
    if source.endswith("return Builder"):
        source = source[: -len("return Builder")].rstrip()
    return source


def render(scene: dict, *, mode: str = "standalone", builder_require: str = "game.ReplicatedStorage.SceneLanguagePrimitives") -> str:
    if mode == "standalone":
        return _render_standalone(scene)
    if mode == "module":
        return _render_module(scene, builder_require)
    raise ValueError(f"Unsupported Roblox render mode: {mode}")


def _render_standalone(scene: dict) -> str:
    lines = _header(scene)
    lines.extend(["local Builder = (function()"])
    lines.extend(_indent_lines(_load_builder_source().splitlines()))
    lines.extend(
        [
            "    return Builder",
            "end)()",
            "",
        ]
    )
    lines.extend(_set_transparency_lines())
    lines.extend(
        [
            f"local existing = workspace:FindFirstChild({scene['scene']!r})",
            "if existing then",
            "    existing:Destroy()",
            "end",
            "",
            "local sceneFolder = Instance.new(\"Folder\")",
            f"sceneFolder.Name = {scene['scene']!r}",
            "sceneFolder.Parent = workspace",
            "",
        ]
    )
    lines.extend(_scene_object_lines(scene))
    return "\n".join(lines).rstrip() + "\n"


def _render_module(scene: dict, builder_require: str) -> str:
    lines = _header(scene)
    body = [
        "return function(parent)",
        f"    local Builder = require({builder_require})",
        "",
    ]
    body.extend(_indent_lines(_set_transparency_lines()))
    body.extend(
        [
            "    local sceneParent = parent or workspace",
            f"    local existing = sceneParent:FindFirstChild({scene['scene']!r})",
            "    if existing then",
            "        existing:Destroy()",
            "    end",
            "",
            "    local sceneFolder = Instance.new(\"Folder\")",
            f"    sceneFolder.Name = {scene['scene']!r}",
            "    sceneFolder.Parent = sceneParent",
            "",
        ]
    )
    body.extend(_indent_lines(_scene_object_lines(scene)))
    body.extend(
        [
            "    return sceneFolder",
            "end",
        ]
    )
    lines.extend(body)
    return "\n".join(lines).rstrip() + "\n"


def _header(scene: dict) -> list[str]:
    return [
        "-- Generated by SGSL",
        f"-- Scene: {scene['scene']}",
        "",
    ]


def _set_transparency_lines() -> list[str]:
    return [
        "local function setTransparency(target, transparency)",
        "    if target:IsA(\"BasePart\") then",
        "        target.Transparency = transparency",
        "        return",
        "    end",
        "",
        "    for _, descendant in ipairs(target:GetDescendants()) do",
        "        if descendant:IsA(\"BasePart\") then",
        "            descendant.Transparency = transparency",
        "        end",
        "    end",
        "end",
        "",
    ]


def _scene_object_lines(scene: dict) -> list[str]:
    lines: list[str] = []
    for obj in scene["objects"]:
        if obj.get("runtime_asset"):
            continue
        if obj["type"] == "marker":
            lines.extend(_render_object(obj, 0, 0, 0))
            continue
        red, green, blue = color_to_rgb(obj["color"])
        lines.extend(_render_object(obj, red, green, blue))
    return lines


def _indent_lines(lines: list[str], spaces: int = 4) -> list[str]:
    prefix = " " * spaces
    return [f"{prefix}{line}" if line else "" for line in lines]


def _render_object(obj: dict, red: int, green: int, blue: int) -> list[str]:
    if obj["type"] == "marker":
        return [
            "do",
            f"    Builder.makeMarker(sceneFolder, {obj['name']!r}, "
            f"Vector3.new({obj['position'][0]}, {obj['position'][1]}, {obj['position'][2]}), "
            f"Vector3.new({obj['rotation'][0]}, {obj['rotation'][1]}, {obj['rotation'][2]}))",
            "end",
            "",
        ]
    if obj["type"] == "frustum":
        return _render_frustum(obj, red, green, blue)
    if obj["type"] == "hollow_frustum":
        if abs(obj["angle"]) < 360:
            return _render_partial_hollow_frustum(obj, red, green, blue)
        fallback = dict(obj)
        fallback["type"] = "frustum"
        fallback["radius_bottom"] = obj["outer_bottom_radius"]
        fallback["radius_top"] = obj["outer_top_radius"]
        return _render_frustum(fallback, red, green, blue)
    if obj["type"] == "profile_revolve":
        return _render_profile_revolve(obj, red, green, blue)
    if obj["type"] == "hollow_pipe_arc":
        return _render_hollow_pipe_arc(obj, red, green, blue)
    if obj["type"] == "spherical_cap":
        return _render_spherical_cap(obj, red, green, blue)
    if obj["type"] == "ring":
        return _render_ring(obj, red, green, blue)
    if obj["type"] == "pipe_arc":
        return _render_expanded(obj, red, green, blue)
    return _render_part(obj, red, green, blue)


def _render_hollow_pipe_arc(obj: dict, red: int, green: int, blue: int) -> list[str]:
    """Use short cylinders as the lightweight Roblox fallback for a curved trough."""
    segments = obj["segments"]
    path_start = math.radians(obj["start_angle"])
    segment_angle = math.radians(obj["angle"]) / segments
    parent_transform = _make_transform(obj["position"], obj["rotation"])
    segment_length = obj["bend_radius"] * abs(segment_angle) * 1.02
    lines: list[str] = []

    for index in range(segments):
        midpoint_angle = path_start + segment_angle * (index + 0.5)
        local_position = [
            obj["bend_radius"] * math.cos(midpoint_angle),
            obj["bend_radius"] * math.sin(midpoint_angle),
            0.0,
        ]
        local_transform = _make_transform(local_position, [0.0, 0.0, math.degrees(midpoint_angle)])
        world_transform = _multiply_transforms(parent_transform, local_transform)
        segment = dict(obj)
        segment["type"] = "cylinder"
        segment["name"] = f"{obj['name']}_segment_{index + 1:02d}"
        segment["radius"] = obj["outer_radius"]
        segment["height"] = segment_length
        segment["position"] = _transform_position(world_transform)
        segment["rotation"] = _transform_rotation(world_transform)
        lines.extend(_render_part(segment, red, green, blue))

    return lines


def _render_profile_revolve(obj: dict, red: int, green: int, blue: int) -> list[str]:
    """Approximate a profile revolve with one generated frustum per profile span."""
    profile = obj["profile"]
    parent_transform = _make_transform(obj["position"], obj["rotation"])
    lines: list[str] = []
    thickness = obj.get("thickness")
    profile_center = (profile[0][0] + profile[-1][0]) / 2

    for index, ((bottom_y, bottom_radius), (top_y, top_radius)) in enumerate(zip(profile, profile[1:]), 1):
        segment = dict(obj)
        segment["type"] = "frustum"
        segment["name"] = f"{obj['name']}_segment_{index:02d}"
        segment["radius_bottom"] = bottom_radius
        segment["radius_top"] = top_radius
        segment["height"] = top_y - bottom_y
        segment["segments"] = obj["segments"]
        segment["position"] = _transform_position(
            _multiply_transforms(
                parent_transform,
                _make_transform(
                    [0.0, (bottom_y + top_y) / 2 - profile_center, 0.0],
                    [0.0, 0.0, 0.0],
                ),
            )
        )
        segment["rotation"] = obj["rotation"]
        if thickness is not None:
            # Roblox Part fallback cannot represent an inner shell; the same
            # profile still remains the single source of truth for its outer wall.
            segment["radius_bottom"] = max(bottom_radius, 0.001)
            segment["radius_top"] = max(top_radius, 0.001)
        lines.extend(_render_frustum(segment, red, green, blue))

    return lines


def _render_partial_hollow_frustum(obj: dict, red: int, green: int, blue: int) -> list[str]:
    """Approximate an open trough with Roblox Parts along its lower arc."""
    segments = obj["segments"]
    start_angle = math.radians(obj["start_angle"])
    segment_angle = math.radians(obj["angle"]) / segments
    outer_radius = (obj["outer_bottom_radius"] + obj["outer_top_radius"]) / 2
    inner_radius = (obj["inner_bottom_radius"] + obj["inner_top_radius"]) / 2
    radial_center = (outer_radius + inner_radius) / 2
    radial_depth = outer_radius - inner_radius
    parent_transform = _make_transform(obj["position"], obj["rotation"])
    lines: list[str] = []

    for index in range(segments):
        midpoint_angle = start_angle + segment_angle * (index + 0.5)
        radial = [math.cos(midpoint_angle), 0.0, math.sin(midpoint_angle)]
        direction = 1.0 if segment_angle >= 0 else -1.0
        tangent = [-math.sin(midpoint_angle) * direction, 0.0, math.cos(midpoint_angle) * direction]
        center = [component * radial_center for component in radial]
        transform = _multiply_transforms(
            parent_transform,
            _basis_transform(center, tangent, [0.0, 1.0, 0.0], radial),
        )
        segment = dict(obj)
        segment["type"] = "block"
        segment["name"] = f"{obj['name']}_segment_{index + 1:02d}"
        segment["size"] = [
            radial_center * abs(segment_angle) * 1.04,
            obj["height"],
            radial_depth,
        ]
        segment["position"] = _transform_position(transform)
        segment["rotation"] = _transform_rotation(transform)
        lines.extend(_render_part(segment, red, green, blue))

    return lines


def _render_part(obj: dict, red: int, green: int, blue: int) -> list[str]:
    x, y, z = obj["position"]
    rx, ry, rz = obj["rotation"]
    transparency = obj["transparency"]
    material = _material_name(obj)
    color_expr = f"Color3.fromRGB({red}, {green}, {blue})"
    material_expr = f"Enum.Material.{material}"
    rotation_expr = f"Vector3.new({rx}, {ry}, {rz})"

    if obj["type"] == "block":
        sx, sy, sz = obj["size"]
        creator = (
            f"Builder.makeBlock(sceneFolder, {obj['name']!r}, "
            f"Vector3.new({sx}, {sy}, {sz}), Vector3.new({x}, {y}, {z}), {color_expr}, {material_expr}, {rotation_expr})"
        )
    elif obj["type"] == "wedge":
        sx, sy, sz = obj["size"]
        creator = (
            f"Builder.makeWedge(sceneFolder, {obj['name']!r}, "
            f"Vector3.new({sx}, {sy}, {sz}), Vector3.new({x}, {y}, {z}), {color_expr}, {material_expr}, {rotation_expr})"
        )
    elif obj["type"] == "cylinder":
        creator = (
            f"Builder.makeCylinder(sceneFolder, {obj['name']!r}, "
            f"{obj['radius']}, {obj['height']}, Vector3.new({x}, {y}, {z}), {color_expr}, {material_expr}, {rotation_expr})"
        )
    else:
        raise ValueError(f"Unsupported render object type: {obj['type']}")

    return [
        "do",
        f"    local part = {creator}",
        f"    setTransparency(part, {transparency})",
        "end",
        "",
    ]


def _render_frustum(obj: dict, red: int, green: int, blue: int) -> list[str]:
    x, y, z = obj["position"]
    rx, ry, rz = obj["rotation"]
    transparency = obj["transparency"]
    material = _material_name(obj)
    return [
        "do",
        "    local model = Builder.makeSteppedFrustum(",
        "        sceneFolder,",
        f"        {obj['name']!r},",
        f"        {obj['radius_bottom']},",
        f"        {obj['radius_top']},",
        f"        {obj['height']},",
        f"        Vector3.new({x}, {y}, {z}),",
        f"        Color3.fromRGB({red}, {green}, {blue}),",
        f"        {obj['segments']},",
        f"        Enum.Material.{material},",
        f"        Vector3.new({rx}, {ry}, {rz})",
        "    )",
        f"    setTransparency(model, {transparency})",
        "end",
        "",
    ]


def _render_ring(obj: dict, red: int, green: int, blue: int) -> list[str]:
    return _render_expanded(obj, red, green, blue)


def _render_spherical_cap(obj: dict, red: int, green: int, blue: int) -> list[str]:
    lines: list[str] = []
    for segment in _expand_spherical_cap(obj):
        lines.extend(_render_frustum(segment, red, green, blue))
    return lines


def _render_expanded(obj: dict, red: int, green: int, blue: int) -> list[str]:
    lines: list[str] = []
    for expanded in iter_render_objects({"scene": "", "objects": [obj]}):
        lines.extend(_render_part(expanded, red, green, blue))
    return lines


def _material_name(obj: dict) -> str:
    explicit_materials = {
        "asphalt": "Asphalt",
        "cobblestone": "Cobblestone",
        "concrete": "Concrete",
        "smoothPlastic": "SmoothPlastic",
        "glass": "Glass",
        "neon": "Neon",
        "pavement": "Pavement",
    }
    if obj["material"] != "auto":
        return explicit_materials[obj["material"]]
    if obj["emissive"] > 0:
        return "Neon"
    if obj["transparency"] > 0:
        return "Glass"
    return "SmoothPlastic"


def write(
    scene: dict,
    output_path: str | Path,
    *,
    mode: str = "standalone",
    builder_require: str = "game.ReplicatedStorage.SceneLanguagePrimitives",
) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(scene, mode=mode, builder_require=builder_require), encoding="utf-8")
    return path
